### ISSUE TITLE
Looks like the tests are broken in anaconda.org

### ISSUE THREAD

**Issue by malev** [Anaconda-Platform/nb_anacondacloud#12]
I've also had issues having them passing in my local computer (osx)
https://anaconda.org/anaconda-nb-extensions/nb_anacondacloud/builds/10/0

**Comment by damianavila** [comment]
ping @bollwyvl

**Comment by bollwyvl** [comment]
Right, that's the focus over on #9.

Here's the current build:
https://anaconda.org/anaconda-nb-extensions/nb_anacondacloud/builds/16

I've blacked out win32/py27 for the known markupsafe issue.

**Comment by bollwyvl** [comment]
@malev over on #9, @damianavila is going to review, then we're going to do a release without win-32 builds... or let the `package.sh` do a best-effort transform.

**Comment by damianavila** [comment]
#9 was merged, so closing here.
