### ISSUE TITLE
Changing the User/Org after initial upload seems to have no effect

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_anacondacloud#28]
I've uploaded a notebook using the extension as the user `tanya`.  I then upload it again as the user `OnTime`.  The subsequent upload still goes into the `tanya` account.

Incidentally, the dialog box that comes up could be a little more informative.  I would suggest saying "Destination account user or organization:"

**Comment by damianavila** [comment]
I can not verify this behavior in the latest AEN, if you see it again, please re-open.
