### ISSUE TITLE
Doesn't install with Anaconda3 v4.3, no Python 3.6 version available

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_anacondacloud#40]
Read the Anaconda 4.3 changelog that suggested I could still install nb_anacondacloud (which I use pretty regularly).  Tried installing it from Navigator, but got this error:

```
UnsatisfiableError:
The following specifications were found to be in conflict:
- nb_anacondacloud -> _nb_ext_conf -> nb_conda -> nb_conda_kernels -> python 2.7* -> openssl 1.0.1*
- python 3.6*
Use "conda info " to see the dependencies for each package.
```

I'm assuming because there is no Python 3.6 version of the package.

**Comment by damianavila** [comment]
Yep, AFAIK there are not yet 3.6 versions available.

**Comment by magic-lantern** [comment]
Any idea when the Python 3.6 version might be made available? Alternatively, is there a manual method to building this?

**Comment by bollard** [comment]
Or, since the other three nb packages (nbpresent, nb_conda, nb_conda_kernels) seem to have 3.6 versions available can the dependencies be uncoupled so we can install one / all as we wish, without having to wait for the lowest/slowest common denominator.

**Comment by damianavila** [comment]
>Any idea when the Python 3.6 version might be made available? 

Hopefully in the next few weeks.

>Alternatively, is there a manual method to building this?

You could take the recipe from conda-forge, tweak them and use them to build the packages locally.

**Comment by damianavila** [comment]
I have built these on conda-forge and it is available there.
It will be available in defaults soon as well.
