### ISSUE TITLE
Toggleable Auto-Publish?

### ISSUE THREAD

**Issue by bollwyvl** [Anaconda-Platform/nb_anacondacloud#7]
> As a User, after I publish a notebook, I want to keep my cloud-published notebook automatically in sync with my local notebook

This came up in the meeting last week as kind of a poor-man's multi-user collaboration. Thoughts and ramblings below...
- Authoring UI
  - "enable auto-publish" checkbox?
  - there's no supported way to make toggle-able button bar buttons... but changing the color/state/icon stack of the button bar icon is _possible_ and would be a good way to show this modal (heh) change 
  - a formal, intentional publish is really good for "major" versions of a notebook, but this would be a lesser publish, and might not be what a user would want to show up by default.
    - would channels work?
  -  is this a per-session kind of thing?
    - if you previously had auto-published enabled, would there be some indicator on next session? toast? _yet another_ button mode?
- consuming UI (anaconda.org)
  - If you are looking at a notebook and new version of the notebook is published, can we notify?
- backend
  -  right now, since we aren't letting tornado do its `yield`y business, doing a publish blocks pretty much everything, whereas File->Save is handled asynchronously. This is probably a good thing to do _anyway_, and would probably just require a little refactoring to put the expensive method into a ThreadPoolExecutor or whatever pattern which has likely been done on other extensions, though we may have to do some custom kernel message.
- Metadata
  - a new field for "auto-publish"?
  - a new field for "auto-publish-throttle" or something, so that compulsive `Cmd+S` people like me aren't making meeelions of notebooks. by the same token, it's always the _last_ save the counts, so perhaps it's more like a tailing debounce, i.e. "publish every time i hit save, unless it's been less than five seconds... but check again in 10 seconds"

@damianavila @malev @mmarchetti @ijstokes

**Comment by mmarchetti** [comment]
I'm a little concerned about the concept of auto-pushing on save. We do automatic saves in the revisioncontrol extension, for example, which might cause unexpected publication. Have we considered the possibility of a simple status widget (dirty bit) that indicates the existence of changes that haven't been uploaded?

**Comment by bollwyvl** [comment]
Ok, let's table this for now!
